import type { Profile, MatchHistory } from '../types';

export const SAMPLE_PROFILES: Record<string, Profile> = {
  "Lukas (Profi)": {
    wins: 9,
    matches: 12,
    dartsThrown: 642,
    pointsScored: 16120,
    highestThrow: 180,
    bestLegDarts: 14,
    highestCheckout: 130,
    sixtyPlus: 32,
    hundredPlus: 28,
    oneFortyPlus: 14,
    oneEighty: 5,
    checkoutAttempts: 34,
    checkoutSuccesses: 18,
    first9Pts: 5400,
    first9Darts: 216,
    color: '#3B82F6',
    triplesHit: 48,
    segmentHits: { "20": 98, "T20": 42, "19": 45, "T19": 18, "D20": 12, "D16": 8, "25": 14, "50": 6 }
  },
  "Stefan (Kneipe)": {
    wins: 4,
    matches: 10,
    dartsThrown: 620,
    pointsScored: 9940,
    highestThrow: 140,
    bestLegDarts: 21,
    highestCheckout: 76,
    sixtyPlus: 22,
    hundredPlus: 12,
    oneFortyPlus: 3,
    oneEighty: 1,
    checkoutAttempts: 46,
    checkoutSuccesses: 8,
    first9Pts: 3100,
    first9Darts: 180,
    color: '#F97316',
    triplesHit: 14,
    segmentHits: { "20": 74, "T20": 12, "19": 36, "T19": 4, "D16": 6, "1": 28, "5": 32 }
  },
  "Leon": {
    wins: 6,
    matches: 8,
    dartsThrown: 410,
    pointsScored: 9020,
    highestThrow: 171,
    bestLegDarts: 16,
    highestCheckout: 116,
    sixtyPlus: 18,
    hundredPlus: 16,
    oneFortyPlus: 8,
    oneEighty: 3,
    checkoutAttempts: 24,
    checkoutSuccesses: 10,
    first9Pts: 3400,
    first9Darts: 144,
    color: '#10B981',
    triplesHit: 28,
    isLinkedCloudGuest: true,
    linkedUsername: 'LeonDarts',
    linkedUserId: 'user_sample_leon',
    syncAuthToken: 'tok_sample_leon',
    segmentHits: { "20": 68, "T20": 26, "19": 32, "T19": 14, "D18": 6, "D20": 8 }
  },
  "Luke 'The Nuke' Bot": {
    wins: 14,
    matches: 18,
    dartsThrown: 820,
    pointsScored: 24100,
    highestThrow: 180,
    bestLegDarts: 12,
    highestCheckout: 164,
    isBot: true,
    targetAverage: 88,
    color: '#A855F7',
    sixtyPlus: 45,
    hundredPlus: 38,
    oneFortyPlus: 22,
    oneEighty: 9,
    checkoutAttempts: 38,
    checkoutSuccesses: 24,
    triplesHit: 72
  }
};

export const SAMPLE_MATCHES: MatchHistory[] = [
  {
    _id: 'sample_match_1',
    date: 'Gestern, 20:15',
    winner: 'Lukas (Profi)',
    gameType: 'standard',
    config: { startScore: 501, outMode: 'DO', setsToWin: 1, legsToWin: 3 },
    players: [
      {
        name: 'Lukas (Profi)',
        sets: 1,
        legs: 3,
        avg: '78.4',
        first9: '84.2',
        matchPts: 1503,
        matchDarts: 58,
        first9Pts: 505,
        first9Darts: 18,
        checkoutAttempts: 6,
        checkoutSuccesses: 3,
        highestCheckout: 108,
        hundredPlus: 7,
        oneFortyPlus: 3,
        oneEighty: 2,
        bestMatchLeg: 14,
        legHistory: ['82.4', '74.1', '78.8']
      },
      {
        name: 'Stefan (Kneipe)',
        sets: 0,
        legs: 1,
        avg: '51.2',
        first9: '54.0',
        matchPts: 1240,
        matchDarts: 73,
        first9Pts: 324,
        first9Darts: 18,
        checkoutAttempts: 8,
        checkoutSuccesses: 1,
        highestCheckout: 32,
        hundredPlus: 2,
        oneFortyPlus: 1,
        oneEighty: 0,
        bestMatchLeg: 22,
        legHistory: ['48.5', '54.2', '50.9', '51.2']
      }
    ]
  },
  {
    _id: 'sample_match_2',
    date: 'Gestern, 21:00',
    winner: 'Leon',
    gameType: 'standard',
    config: { startScore: 501, outMode: 'DO', setsToWin: 1, legsToWin: 2 },
    players: [
      {
        name: 'Leon',
        sets: 1,
        legs: 2,
        avg: '71.6',
        first9: '76.0',
        matchPts: 1002,
        matchDarts: 42,
        first9Pts: 456,
        first9Darts: 18,
        checkoutAttempts: 4,
        checkoutSuccesses: 2,
        highestCheckout: 116,
        hundredPlus: 4,
        oneFortyPlus: 2,
        oneEighty: 1,
        bestMatchLeg: 16,
        legHistory: ['74.2', '69.0'],
        isLinkedCloudGuest: true,
        linkedUsername: 'LeonDarts',
        linkedUserId: 'user_sample_leon'
      },
      {
        name: 'Lukas (Profi)',
        sets: 0,
        legs: 1,
        avg: '69.8',
        first9: '72.5',
        matchPts: 884,
        matchDarts: 38,
        first9Pts: 435,
        first9Darts: 18,
        checkoutAttempts: 3,
        checkoutSuccesses: 1,
        highestCheckout: 40,
        hundredPlus: 3,
        oneFortyPlus: 2,
        oneEighty: 1,
        bestMatchLeg: 18,
        legHistory: ['72.0', '67.6']
      }
    ]
  },
  {
    _id: 'sample_match_3',
    date: 'Vorgestern, 19:30',
    winner: 'Team 1 (Lukas & Leon)',
    gameType: 'standard',
    is2v2: true,
    config: { startScore: 501, outMode: 'DO', setsToWin: 1, legsToWin: 2, is2v2: true },
    players: [
      {
        name: 'Lukas (Profi)',
        team: 1,
        sets: 1,
        legs: 2,
        avg: '74.5',
        first9: '79.2',
        matchPts: 620,
        matchDarts: 25,
        checkoutAttempts: 2,
        checkoutSuccesses: 1,
        highestCheckout: 64,
        hundredPlus: 3,
        oneFortyPlus: 1,
        oneEighty: 1
      },
      {
        name: 'Stefan (Kneipe)',
        team: 2,
        sets: 0,
        legs: 0,
        avg: '48.2',
        first9: '50.1',
        matchPts: 410,
        matchDarts: 26,
        checkoutAttempts: 3,
        checkoutSuccesses: 0,
        highestCheckout: 0,
        hundredPlus: 1,
        oneFortyPlus: 0,
        oneEighty: 0
      },
      {
        name: 'Leon',
        team: 1,
        sets: 1,
        legs: 2,
        avg: '68.9',
        first9: '73.0',
        matchPts: 382,
        matchDarts: 17,
        checkoutAttempts: 2,
        checkoutSuccesses: 1,
        highestCheckout: 48,
        hundredPlus: 2,
        oneFortyPlus: 1,
        oneEighty: 0,
        isLinkedCloudGuest: true,
        linkedUsername: 'LeonDarts'
      },
      {
        name: 'Gast 1',
        team: 2,
        sets: 0,
        legs: 0,
        avg: '44.0',
        first9: '46.0',
        matchPts: 340,
        matchDarts: 23,
        checkoutAttempts: 1,
        checkoutSuccesses: 0,
        highestCheckout: 0,
        hundredPlus: 0,
        oneFortyPlus: 0,
        oneEighty: 0
      }
    ]
  },
  {
    _id: 'sample_match_4',
    date: 'Vor 3 Tagen, 17:45',
    winner: 'Lukas (Profi)',
    gameType: 'powerScoring',
    players: [
      {
        name: 'Lukas (Profi)',
        sets: 1,
        legs: 1,
        avg: '83.4',
        first9: '83.4',
        score: 584,
        attempts: 21,
        matchPts: 584,
        matchDarts: 21
      }
    ]
  }
];

export const SAMPLE_PROFILE_KEYS = Object.keys(SAMPLE_PROFILES);
